<?php

/**
 * Danh sách 113 phường của Thành phố Hồ Chí Minh (sau sắp xếp đơn vị hành chính cấp xã, hiệu lực từ 01/07/2025,
 * theo Nghị quyết 1685/NQ-UBTVQH15). Dùng cho ô chọn "Địa chỉ" ở form đăng ký / sửa người dùng
 * và để kiểm tra (Rule::in) giá trị địa chỉ gửi lên phải nằm trong danh sách này.
 * Không gồm 54 xã và đặc khu Côn Đảo vì đề tài chỉ cho chọn phường.
 */
return [
    'Phường An Đông',
    'Phường An Hội Đông',
    'Phường An Hội Tây',
    'Phường An Khánh',
    'Phường An Lạc',
    'Phường An Nhơn',
    'Phường An Phú',
    'Phường An Phú Đông',
    'Phường Bà Rịa',
    'Phường Bàn Cờ',
    'Phường Bảy Hiền',
    'Phường Bến Cát',
    'Phường Bến Thành',
    'Phường Bình Cơ',
    'Phường Bình Dương',
    'Phường Bình Đông',
    'Phường Bình Hòa',
    'Phường Bình Hưng Hòa',
    'Phường Bình Lợi Trung',
    'Phường Bình Phú',
    'Phường Bình Quới',
    'Phường Bình Tân',
    'Phường Bình Tây',
    'Phường Bình Thạnh',
    'Phường Bình Thới',
    'Phường Bình Tiên',
    'Phường Bình Trị Đông',
    'Phường Bình Trưng',
    'Phường Cát Lái',
    'Phường Cầu Kiệu',
    'Phường Cầu Ông Lãnh',
    'Phường Chánh Hiệp',
    'Phường Chánh Hưng',
    'Phường Chánh Phú Hòa',
    'Phường Chợ Lớn',
    'Phường Chợ Quán',
    'Phường Dĩ An',
    'Phường Diên Hồng',
    'Phường Đông Hòa',
    'Phường Đông Hưng Thuận',
    'Phường Đức Nhuận',
    'Phường Gia Định',
    'Phường Gò Vấp',
    'Phường Hạnh Thông',
    'Phường Hiệp Bình',
    'Phường Hòa Bình',
    'Phường Hòa Hưng',
    'Phường Hòa Lợi',
    'Phường Khánh Hội',
    'Phường Lái Thiêu',
    'Phường Linh Xuân',
    'Phường Long Bình',
    'Phường Long Hương',
    'Phường Long Nguyên',
    'Phường Long Phước',
    'Phường Long Trường',
    'Phường Minh Phụng',
    'Phường Nhiêu Lộc',
    'Phường Phú An',
    'Phường Phú Định',
    'Phường Phú Lâm',
    'Phường Phú Lợi',
    'Phường Phú Mỹ',
    'Phường Phú Nhuận',
    'Phường Phú Thạnh',
    'Phường Phú Thọ',
    'Phường Phú Thọ Hòa',
    'Phường Phú Thuận',
    'Phường Phước Long',
    'Phường Phước Thắng',
    'Phường Rạch Dừa',
    'Phường Sài Gòn',
    'Phường Tam Bình',
    'Phường Tam Long',
    'Phường Tam Thắng',
    'Phường Tăng Nhơn Phú',
    'Phường Tân Bình',
    'Phường Tân Định',
    'Phường Tân Đông Hiệp',
    'Phường Tân Hải',
    'Phường Tân Hiệp',
    'Phường Tân Hòa',
    'Phường Tân Hưng',
    'Phường Tân Khánh',
    'Phường Tân Mỹ',
    'Phường Tân Phú',
    'Phường Tân Phước',
    'Phường Tân Sơn',
    'Phường Tân Sơn Hòa',
    'Phường Tân Sơn Nhất',
    'Phường Tân Sơn Nhì',
    'Phường Tân Tạo',
    'Phường Tân Thành',
    'Phường Tân Thới Hiệp',
    'Phường Tân Thuận',
    'Phường Tân Uyên',
    'Phường Tây Nam',
    'Phường Tây Thạnh',
    'Phường Thạnh Mỹ Tây',
    'Phường Thông Tây Hội',
    'Phường Thới An',
    'Phường Thới Hòa',
    'Phường Thủ Dầu Một',
    'Phường Thủ Đức',
    'Phường Thuận An',
    'Phường Thuận Giao',
    'Phường Trung Mỹ Tây',
    'Phường Vĩnh Hội',
    'Phường Vĩnh Tân',
    'Phường Vũng Tàu',
    'Phường Vườn Lài',
    'Phường Xóm Chiếu',
    'Phường Xuân Hòa',
];
